# Generated by Django 4.2.8 on 2024-01-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
